/* WEB 配置页内嵌 HTML(面向小白: 状态栏/分组/快捷配色) —— 自 web.c 拆出的纯常量 */
const char web_page[] =
"<!DOCTYPE html><html lang=zh><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>BB机设置</title><style>"
"body{font-family:system-ui;max-width:560px;margin:16px auto;padding:0 12px;background:#141a14;color:#c8e0c0}"
"h1{font-size:18px;margin:0 0 4px}.sub{font-size:12px;color:#8a9a8a;margin-bottom:12px}"
".st{font-size:13px;padding:8px;border-radius:6px;margin-bottom:12px}.st.ok{background:#123a1a;color:#90e0a0}.st.no{background:#3a2412;color:#ffb070}"
"h2{font-size:14px;color:#8fd48a;border-bottom:1px solid #2a4a2a;padding-bottom:4px;margin:18px 0 8px}"
"label{display:block;margin:8px 0 2px;font-size:13px;color:#a8c8a0}"
"input[type=text],input[type=password],input[type=number],select{width:200px;background:#0e120e;color:#e8f0e8;border:1px solid #3a5a3a;padding:5px}"
"textarea{width:100%;height:200px;box-sizing:border-box;background:#0e120e;color:#e8f0e8;border:1px solid #3a5a3a}"
".row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:4px 0}.row label{margin:0}"
"input[type=color]{width:52px;height:28px;border:0;background:none;vertical-align:middle}"
".hint{font-size:12px;color:#6a8a6a}.alarm{display:flex;gap:8px;align-items:center;margin:4px 0;flex-wrap:wrap}.alarm input[type=number]{width:60px}.alarm input[type=checkbox]{width:auto}"
".btns{margin:16px 0 24px;display:flex;gap:10px;flex-wrap:wrap}button{padding:10px 20px;font-size:15px;border:0;border-radius:6px;cursor:pointer}"
"#save{background:#2a6a2a;color:#e8ffe8}#beepbtn{background:#3a3a5a;color:#e0e0ff}#reboot{background:#5a2a2a;color:#ffe0e0}"
"#msg{margin:6px 0;font-size:14px;color:#90e090;min-height:18px}</style></head><body>"
"<h1>📟 BB 机设置</h1><div class=sub>给传呼机设置 WiFi、指令、外观、闹钟。改完点「保存到设备」。</div>"
"<div class='st' id=st>加载中…</div>"
"<h2>① 连上家里的 WiFi</h2><div class=hint>点「扫描」选你家 WiFi 填密码; 手机也要连同一个 WiFi 才能继续用网页。</div>"
"<button id=scanwifi type=button style='background:#1f5f9f;color:#fff;padding:8px 16px;border:0;border-radius:6px;margin-bottom:8px'>扫描附近 WiFi</button>"
"<div id=wifilist style='max-height:180px;overflow:auto;border:1px solid #3a5a3a;border-radius:4px;margin-bottom:8px;display:none'></div>"
"<label>WiFi 名</label><input id=ssid type=text placeholder='扫描选择或手输'>"
"<label>WiFi 密码(已配置不回显, 星号=保持不变)</label><input id=pass type=password>"
"<div class=row><button id=clrwifi type=button style='background:#5a2a2a;color:#fff;padding:6px 14px;border:0;border-radius:6px' onclick=clrwifi()>清除已存WiFi(回配网模式)</button></div>"
"<label>天气城市(拼音)</label><input id=city type=text placeholder='chengdu / beijing'>"
"<label>天气 API 私钥(心知天气)</label><input id=key type=text placeholder='留空用内置默认'>"
"<h2>② 指令库(神谕随机抽取)</h2><div class=hint>每行一条; 支持 {#FF0000}颜色 / {RAND:1-10}随机数 / {TODO}待办</div><textarea id=ins></textarea>"
"<h2>②b 64 大字指令库(64px时使用)</h2><div class=hint>每行一条; 同样支持 {#RRGGBB} / {RAND} / {TODO}</div><textarea id=ins64></textarea>"
"<h2>⑨ 答案之书(询问)</h2><div class=hint>文本框显示并编辑该分类【全部】答案(内置+自定义); 每行一条, 保存到设备生效; 清空保存=恢复内置默认</div>"
"<div class=row><b style=color:#8fd48a>回答</b></div><textarea id=ans0 rows=4 style='width:100%;box-sizing:border-box'></textarea>"
"<div class=row><b style=color:#8fd48a>吃什么</b></div><textarea id=ans1 rows=3 style='width:100%;box-sizing:border-box'></textarea>"
"<div class=row><b style=color:#8fd48a>喝什么</b></div><textarea id=ans2 rows=3 style='width:100%;box-sizing:border-box'></textarea>"
"<div class=row><b style=color:#8fd48a>玩什么</b></div><textarea id=ans3 rows=3 style='width:100%;box-sizing:border-box'></textarea>"
"<label>当前使用者(无「致X:」的指令自动加致TA)</label><div class=row><select id=user></select>"
"<input id=useradd type=text placeholder='新名字' style='width:80px'><button onclick=userAdd() style='background:#2a5a8f;color:#fff;padding:4px 10px;border:0;border-radius:4px'>添加</button></div>"
"<h2>③ 外观(主题色)</h2>"
"<div class=row><label>快捷配色</label><select id=preset onchange=preset(this.value)><option value=''>自定义</option></select></div>"
"<div class=row id=cols></div>"
"<h2>破译外观</h2><div class=hint>乱码破译的真字色/乱码色/速度/字号(行数自动匹配)；颜色直接输入 #RRGGBB，例如 #63A2EF</div>"
"<div class=row><label>真字 <span id=gdef_prev style='display:inline-block;width:20px;height:20px;background:#63A2EF;border:1px solid #888;vertical-align:middle'></span> <input id=gdef type=color value='#63A2EF' style='width:40px;height:28px' oninput=\"colorSync('gdef','gdef_text','gdef_prev')\"> <input id=gdef_text type=text value='#63A2EF' maxlength=7 style='width:80px' oninput='gdefText()'></label><label>乱码 <span id=ggb_prev style='display:inline-block;width:20px;height:20px;background:#3A5A8A;border:1px solid #888;vertical-align:middle'></span> <input id=ggb type=color value='#3A5A8A' style='width:40px;height:28px' oninput=\"colorSync('ggb','ggb_text','ggb_prev')\"> <input id=ggb_text type=text value='#3A5A8A' maxlength=7 style='width:80px' oninput='ggbText()'></label></div>"
"<div class=row><label>乱码刷新 <input id=gdl type=number min=5 max=100 style='width:64px'>ms</label><label>逐字揭示 <input id=grv type=number min=10 max=300 style='width:64px'>ms</label>"
"<label>字号 <select id=gfnt><option value=0>16px</option><option value=1>24px</option><option value=2>32px</option><option value=3>64px</option></select></label></div>"
"<h2>④ 闹钟</h2><div class=hint>最多16个; 点下方「+ 添加闹钟」增加, 每行可删; 模式=每天/工作日/周末/一次性/自定义, 到点屏幕显示「今日指令」</div><div id=alarms></div>"
"<h2>⑤ 声音与系统</h2>"
"<div class=row><label>蜂鸣器 <input id=beep type=checkbox style='width:auto'></label><label>音量 <input id=vol type=number min=0 max=100></label></div>"
"<div class=row><label>按键音 <select id=key_sound><option value=0>关</option><option value=1>音频</option></select></label><label>主题 <select id=theme><option value=0>柔和绿</option><option value=1>赛博青</option><option value=2>深夜黑</option><option value=3>标准黑白</option></select></label></div>"
"<div class=row><label>熄屏 <select id=timeout><option value=30>30秒</option><option value=60>1分</option><option value=300>5分</option><option value=0>永不</option></select></label>"
"<label>神谕 <select id=on><option value=0>关</option><option value=1>1条</option><option value=3>3条</option><option value=5>5条</option><option value=9>9条</option></select></label>"
"<label>时段 <select id=ow><option value=0>白天</option><option value=1>全天</option><option value=2>晚上</option><option value=3>凌晨</option></select></label></div>"
"<div class=row><label>光标 <select id=cursor><option value=0>白线</option><option value=1>白块</option><option value=2>角框</option></select></label><label>平衡互换 <select id=shake_swap><option value=0>关</option><option value=1>开</option></select></label></div>"
"<div class=row><label>息屏时钟自动乱码 <select id=aod_auto><option value=0>关</option><option value=1>开(1~30秒随机)</option></select></label><label>长按速度 <select id=long_speed><option value=0>慢</option><option value=1 selected>中</option><option value=2>快</option></select></label></div>"
"<div class=btns><button id=save onclick=save()>保存到设备</button><button id=beepbtn onclick=beep()>试响</button><button id=reboot onclick=reboot()>重启设备</button></div>"
"<div id=msg></div>"
"<h2>⑥ 抽卡图鉴</h2><div class=hint>已抽中的人格才可拼点。★=已抽, ▢=还没抽到</div>"
"<div class=row>共 <b id=gtotal>0</b> 个 · 已抽 <b id=gowned>0</b> 个</div>"
"<div id=gacha style='font-size:12px;max-height:260px;overflow:auto;border:1px solid #3a5a3a;border-radius:4px;padding:6px;margin-top:6px'></div>"
"<h2>⑦ 待办(指令日志)</h2><div class=hint>要执行的事; 指令前加 {TODO} 会在设备破译时自动存入</div>"
"<div class=row><input id=txt type=text placeholder='要执行的事' style='flex:1'><button onclick=todoAdd() style='background:#2a5a8f;color:#fff;padding:8px 16px;border:0;border-radius:6px'>添加</button><button onclick=todoClear() style='background:#5a2a2a;color:#fff;padding:8px 16px;border:0;border-radius:6px'>清空</button></div>"
"<div id=todolist></div>"
"<h2>OTA 固件升级</h2><div class=hint>填固件直链(如 GitHub Release 的 oder.bin)与 SHA256；保存后到设备“联网→版本更新”开始升级</div>"
"<div class=row><label>固件 URL <input id=otaurl type=text style=width:100% placeholder='https://github.com/.../oder.bin'></label></div>"
"<div class=row><label>SHA256(可留空) <input id=otasha type=text style=width:100% placeholder='64位 hex,留空则跳过校验'></label></div>"
"<h2>☁ 云端 OneNET(可选)</h2><div class=hint>填 OneNET 三元组并启用: 电量/闹钟/待办提醒/每日神谕上报云端, 平台可下发屏幕指令; 启用期间设备保持在线不进待机(耗电增加)。平台侧物模型请按 README「云端 OneNET」章节创建</div>"
"<div class=row><label>启用 <input id=cloud_on type=checkbox style='width:auto'></label><label>状态 <b id=cloud_st></b></label></div>"
"<label>产品ID ProductID</label><input id=cloud_pid type=text placeholder='如 24AbCdEf'>"
"<label>设备名 DeviceName</label><input id=cloud_name type=text placeholder='如 beeper01'>"
"<label>设备密钥 DeviceKey(已配置不回显, 星号=保持不变; 换设备请先清空)</label><input id=cloud_key type=text placeholder='base64 密钥'>"
"<div class=row><button onclick=cloudSave() style='background:#1f5f9f;color:#fff;padding:6px 14px;border:0;border-radius:6px'>保存云端配置</button></div>"
"<h2>⑧ 设备状态</h2><div id=devst class=hint>加载中…</div><button onclick=devst() style='background:#2a5a8f;color:#fff;padding:8px 16px;border:0;border-radius:6px;margin-top:6px'>刷新</button>"
"<h2>📨 发指令给 BB 机</h2><div class=hint>输入文字点发送, 设备立刻乱码破译显示</div>"
"<div class=row><input id=sendtxt type=text placeholder='如: 去喝水' maxlength='96' style='flex:1'><button onclick=sendcmd() style='background:#2a5a8f;color:#fff;padding:8px 16px;border:0;border-radius:6px'>发送</button></div>"
"<div id=msg2></div>"
"<script>"
"let TOK='';"
"async function gettok(){if(!TOK){try{TOK=(await (await fetch('/api/token')).json()).token||'';}catch(e){}}return TOK;}"
"async function post(u,b){await gettok();return fetch(u,{method:'POST',headers:b?{'Content-Type':'application/json','X-Web-Token':TOK}:{'X-Web-Token':TOK},body:b?JSON.stringify(b):undefined});}"
"const COLS=['bg','menu','frame','icon','time','date'],CN=['背景','菜单','选中框','图标','时钟','日期'];\n"
"function esc(s){return String(s).replace(/[&<>\"']/g,function(c){return '&#'+c.charCodeAt(0)+';';});}"
"function colorSync(src,dst,prev){var v=document.getElementById(src).value;document.getElementById(dst).value=v;document.getElementById(prev).style.background=v;}"
"function gdefText(){var v=document.getElementById('gdef_text').value;if(/^#[0-9a-fA-F]{6}$/.test(v)){document.getElementById('gdef').value=v;document.getElementById('gdef_prev').style.background=v;}}"
"function ggbText(){var v=document.getElementById('ggb_text').value;if(/^#[0-9a-fA-F]{6}$/.test(v)){document.getElementById('ggb').value=v;document.getElementById('ggb_prev').style.background=v;}}"
"const P={'护眼绿':{bg:'141A14',menu:'C8E0C0',frame:'8FD48A',icon:'7FD0D0',time:'C8E0C0',date:'C8E0C0'},'标准黑白':{bg:'000000',menu:'FFFFFF',frame:'FFFFFF',icon:'FFFFFF',time:'FFFFFF',date:'FFFFFF'},'深空黑':{bg:'101018',menu:'C0C0D8',frame:'7080F0',icon:'40A0E0',time:'C0C0D8',date:'808090'},'暖橙':{bg:'181410',menu:'E0D0C0',frame:'FF9040',icon:'FFB070',time:'E0D0C0',date:'A08060'},'星云紫':{bg:'141018',menu:'D8C8E8',frame:'A070F0',icon:'80C0F0',time:'D8C8E8',date:'807090'},'赛博青':{bg:'081018',menu:'B8E8F0',frame:'20C8F0',icon:'F060D0',time:'B8E8F0',date:'508090'},'落日橙':{bg:'1A1008',menu:'F0D0A8',frame:'FF8030',icon:'FFC060',time:'F0D0A8',date:'907050'},'樱花粉':{bg:'180E12',menu:'F0C8D8',frame:'F078A8',icon:'C8A0F0',time:'F0C8D8',date:'805060'},'薄荷绿':{bg:'0C1810',menu:'C8F0DC',frame:'40E090',icon:'80E0C0',time:'C8F0DC',date:'508070'}};"
"Object.keys(P).forEach(k=>document.getElementById('preset').insertAdjacentHTML('beforeend','<option>'+k+'</option>'));"
"function preset(k){if(!P[k])return;Object.keys(P[k]).forEach(c=>document.getElementById('col_'+c).value='#'+P[k][c]);}"
"function amd(d,o){if(o)return'once';if(d==127)return'day';if(d==62)return'work';if(d==65)return'wknd';return'cust';}"
"function almhtml(a,i){let m=amd(a.days,a.once),s='<div class=alarm><label style=font-size:11px><input id=en_'+i+' type=checkbox'+(a.en?' checked':'')+'>启用</label><input id=hh_'+i+' type=number min=0 max=23 value='+a.hh+'><b>:</b><input id=mm_'+i+' type=number min=0 max=59 value='+a.mm+'><select id=md_'+i+' onchange=almMode('+i+',this.value)><option value=day'+(m=='day'?' selected':'')+'>每天</option><option value=work'+(m=='work'?' selected':'')+'>工作日</option><option value=wknd'+(m=='wknd'?' selected':'')+'>周末</option><option value=once'+(m=='once'?' selected':'')+'>一次性</option><option value=cust'+(m=='cust'?' selected':'')+'>自定义</option></select><span>';"
"['日','一','二','三','四','五','六'].forEach(function(d,k){s+='<label style=font-size:11px><input type=checkbox id=dw'+i+'_'+k+(a.days&(1<<k)?' checked':'')+'>'+d+'</label>';});"
"s+='<button onclick=almDel('+i+') style=padding:1px 6px;color:#ffb070>删</button></div>';return s;}"
"function almMode(i,m){let days=m=='day'?127:m=='work'?62:m=='wknd'?65:m=='cust'?(AL[i].days||127):127;for(let k=0;k<7;k++){let c=document.getElementById('dw'+i+'_'+k);if(c)c.checked=!!(days&(1<<k));}if(m=='once'){for(let k=0;k<7;k++){let c=document.getElementById('dw'+i+'_'+k);if(c)c.checked=true;}}}"
"let ready=0,AL=[];"
"function almRender(){let h=(AL||[]).map((a,i)=>almhtml(a,i)).join('');"
"h+='<div style=margin-top:6px><button onclick=almAdd() style=background:#2a5a8f;color:#fff;padding:6px 14px;border:0;border-radius:6px>+ 添加闹钟</button></div>';"
"document.getElementById('alarms').innerHTML=h;}"
"function almAdd(){if(!ready){alert('页面还没加载完，请稍等');return;}if((AL||[]).length>=16){alert('最多16个闹钟');return;}AL.push({en:1,hh:8,mm:0,days:127,once:0});almRender();}"
"function almDel(i){AL.splice(i,1);almRender();}"
"async function load(){let j=await (await fetch('/api/cfg')).json(),st=document.getElementById('st');"
"if(j.status.wifi){st.className='st ok';st.textContent='已连 WiFi · '+j.status.ip+' · 手机/电脑打开 http://'+j.status.ip+'/';}"
"else{st.className='st no';st.textContent='未连 WiFi: 先连热点「'+j.ap_ssid+'」(密码 '+j.ap_pass+'), 再开 http://192.168.4.1/';}"
"document.getElementById('ssid').value=j.wifi.ssid;document.getElementById('pass').value=j.wifi.pass;document.getElementById('city').value=j.city;document.getElementById('key').value=j.key||'';"
"document.getElementById('ins').value=(j.ins||[]).join('\\n');document.getElementById('ins64').value=(j.ins64||[]).join('\\n');"
"document.getElementById('ans0').value=j.ans&&j.ans.c0||'';document.getElementById('ans1').value=j.ans&&j.ans.c1||'';document.getElementById('ans2').value=j.ans&&j.ans.c2||'';document.getElementById('ans3').value=j.ans&&j.ans.c3||'';"
"let uo=j.users.map(u=>'<option'+(u==j.user?' selected':'')+'>'+esc(u)+'</option>').join('');if(j.users.indexOf(j.user)<0)uo+='<option selected>'+esc(j.user)+'</option>';document.getElementById('user').innerHTML=uo;"
"document.getElementById('cols').innerHTML=COLS.map((c,i)=>'<span>'+CN[i]+'<input type=color id=col_'+c+' value=#'+j.colors[c]+'></span>').join('');"
"document.getElementById('otaurl').value=j.ota&&j.ota.url||'';document.getElementById('otasha').value=j.ota&&j.ota.sha256||'';AL=j.alarms||[];almRender();"   /* 不过滤 en=0: 设备端关闭/一次性触发后的闹钟也要显示可恢复, 保存时全量回传保留字段 */
"document.getElementById('beep').checked=j.beep?1:0;document.getElementById('vol').value=j.vol;document.getElementById('key_sound').value=j.key_sound;document.getElementById('theme').value=j.theme;"
"document.getElementById('timeout').value=j.timeout;document.getElementById('on').value=j.oracle_n;document.getElementById('ow').value=j.oracle_win;"
"document.getElementById('cursor').value=j.cursor;document.getElementById('shake_swap').value=j.shake_swap;document.getElementById('aod_auto').value=j.aod_auto;document.getElementById('long_speed').value=j.long_speed;"
"var gd='#'+j.garble.def,gg='#'+j.garble.gb;document.getElementById('gdef').value=gd;document.getElementById('gdef_text').value=gd;document.getElementById('gdef_prev').style.background=gd;document.getElementById('ggb').value=gg;document.getElementById('ggb_text').value=gg;document.getElementById('ggb_prev').style.background=gg;"
"document.getElementById('gdl').value=j.garble.dl;document.getElementById('grv').value=j.garble.rv;document.getElementById('gfnt').value=j.garble.fnt;ready=1;}"
"async function userAdd(){let n=document.getElementById('useradd').value.trim();if(!n)return;let r=await(await post('/api/user',{name:n})).json();if(r.ok){let s=document.getElementById('user');if(![...s.options].some(o=>o.value==n))s.insertAdjacentHTML('beforeend','<option>'+esc(n)+'</option>');s.value=n;document.getElementById('useradd').value='';}else{alert('添加失败');}}"
"async function save(){if(!ready){alert('页面还没加载完，请稍等');return;}let cols={},alarms=[];"
"COLS.forEach(c=>cols[c]=document.getElementById('col_'+c).value.slice(1));"
"let na=document.querySelectorAll('#alarms .alarm').length;"
"for(let i=0;i<na;i++){let m=document.getElementById('md_'+i).value,days=127,once=0;"
"if(m=='work')days=62;else if(m=='wknd')days=65;else if(m=='once'){days=127;once=1;}"
"else if(m=='cust'){days=0;for(let k=0;k<7;k++)if(document.getElementById('dw'+i+'_'+k).checked)days|=1<<k;}"
"alarms.push({idx:AL[i].idx,en:document.getElementById('en_'+i).checked?1:0,hh:+document.getElementById('hh_'+i).value,mm:+document.getElementById('mm_'+i).value,days:days,once:once});}"
"let body={colors:cols,ins:document.getElementById('ins').value,ins64:document.getElementById('ins64').value,user:document.getElementById('user').value,alarms:alarms,"
"wifi:{ssid:document.getElementById('ssid').value,pass:document.getElementById('pass').value},"
"city:document.getElementById('city').value,key:document.getElementById('key').value,beep:document.getElementById('beep').checked?1:0,vol:+document.getElementById('vol').value,key_sound:+document.getElementById('key_sound').value,theme:+document.getElementById('theme').value,"
"timeout:+document.getElementById('timeout').value,oracle_n:+document.getElementById('on').value,oracle_win:+document.getElementById('ow').value,"
"cursor:+document.getElementById('cursor').value,shake_swap:+document.getElementById('shake_swap').value,aod_auto:+document.getElementById('aod_auto').value,long_speed:+document.getElementById('long_speed').value,"
"garble:{def:document.getElementById('gdef_text').value.slice(1),gb:document.getElementById('ggb_text').value.slice(1),dl:+document.getElementById('gdl').value,rv:+document.getElementById('grv').value,fnt:+document.getElementById('gfnt').value},"
"ota:{url:document.getElementById('otaurl').value,sha256:document.getElementById('otasha').value},ans:{c0:document.getElementById('ans0').value,c1:document.getElementById('ans1').value,c2:document.getElementById('ans2').value,c3:document.getElementById('ans3').value}};"
"let j=await (await post('/api/cfg',body)).json();"
"document.getElementById('msg').textContent=j.ok?'✓ 已保存':'保存失败';}"
"async function beep(){await post('/api/beep');}"
"async function reboot(){if(confirm('确定重启 BB 机?')){await post('/api/reboot');document.getElementById('msg').textContent='重启中…';}}"
"async function clrwifi(){if(!confirm('清除已存 WiFi 并回到配网模式?'))return;try{await post('/api/clearwifi');}catch(e){}document.getElementById('msg').textContent='已清除,请连接 ESP32ODERAP 重新配网';}"
"document.getElementById('scanwifi').onclick=async function(){let b=this;b.disabled=1;b.textContent='扫描中…';"
"let l=document.getElementById('wifilist');l.innerHTML='';l.style.display='block';"
"try{await post('/api/scan');let j={busy:1},tries=0;"   /* 扫描已改为后台任务: POST 启动后轮询结果 */
"while(j.busy&&tries<25){await new Promise(r=>setTimeout(r,400));j=await (await fetch('/api/scanres')).json();tries++;}"
"if(j.busy){l.innerHTML='<div style=padding:8px;color:#ffb070>扫描超时,请重试</div>';}"
"else if(!j.wifi_list||!j.wifi_list.length){l.innerHTML='<div style=padding:8px;color:#ffb070>没扫到 WiFi</div>';}"
"else j.wifi_list.forEach(function(w){let d=document.createElement('div');"
"d.style.cssText='padding:7px 10px;border-bottom:1px solid #2a4a2a;cursor:pointer;display:flex;justify-content:space-between;font-size:14px';"
"d.innerHTML=(w.encrypted?'🔒 ':'🌐 ')+esc(w.ssid)+'<span style=color:#8a9a8a>'+w.rssi+'dBm</span>';"
"d.onclick=function(){document.getElementById('ssid').value=w.ssid;document.getElementById('pass').focus();};l.appendChild(d);});}"
"catch(e){l.innerHTML='<div style=padding:8px;color:#ffb070>扫描失败</div>';}"
"b.disabled=0;b.textContent='重新扫描 WiFi';};"
"async function sendcmd(){let t=document.getElementById('sendtxt').value;if(!t)return;"
"let j=await (await post('/api/send',{cmd:t})).json();"
"document.getElementById('msg2').textContent='已发送, 设备正在显示';}"
"async function gacha(){let j=await (await fetch('/api/gacha')).json();"
"document.getElementById('gtotal').textContent=j.total;document.getElementById('gowned').textContent=j.owned;"
"let h='';j.sinners.forEach(function(s){"
"h+='<div style=color:#8fd48a;font-size:13px;margin:4px 0 2px>'+esc(s.name)+' '+s.owned+'/'+s.total+'</div>';"
"s.items.forEach(function(it){h+='<div style=padding-left:14px;font-size:12px;color:'+(it.owned?'#c8e0c0':'#6a8a6a')+'>'+(it.owned?'★ ':'▢ ')+esc(it.name)+'</div>';});});"
"document.getElementById('gacha').innerHTML=h;}"
"gacha();"
"async function todoLoad(){let j=await (await fetch('/api/todo')).json();let h='';(j.todos||[]).forEach(function(t,i){h+='<div style=padding:6px 4px;border-bottom:1px solid #2a4a2a;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap>'+(t.done?'<span style=color:#6a8a6a>✓ '+esc(t.text)+'</span>':'<span>'+esc(t.text)+'</span>')+'<span style=font-size:11px><input id=rem_en_'+i+' type=checkbox'+(t.remind_en?' checked':'')+'>提醒 <input id=rem_hh_'+i+' type=number min=0 max=23 style=width:48px value='+(t.remind_hh||0)+'>:<input id=rem_mm_'+i+' type=number min=0 max=59 style=width:48px value='+(t.remind_mm||0)+'><button onclick=todoRemind('+i+') style=padding:2px 6px>设提醒</button></span><span><button onclick=todoToggle('+i+') style=padding:3px 8px>'+(t.done?'恢复':'PASS')+'</button><button onclick=todoDel('+i+') style=padding:3px 8px>删除</button></span></div>';});document.getElementById('todolist').innerHTML=h||'<div style=color:#6a8a6a>还没有待办</div>';}"
"async function todoAdd(){let t=document.getElementById('txt').value;if(!t)return;await post('/api/todo',{op:'add',text:t});document.getElementById('txt').value='';todoLoad();}"
"async function todoToggle(i){await post('/api/todo',{op:'toggle',idx:i});todoLoad();}"
"async function todoRemind(i){let en=document.getElementById('rem_en_'+i).checked?1:0,hh=+document.getElementById('rem_hh_'+i).value,mm=+document.getElementById('rem_mm_'+i).value;await post('/api/todo',{op:'remind',idx:i,en:en,hh:hh,mm:mm});todoLoad();}"
"async function todoDel(i){await post('/api/todo',{op:'del',idx:i});todoLoad();}"
"async function todoClear(){if(confirm('清空全部待办?')){await post('/api/todo',{op:'clear'});todoLoad();}}"
"async function devst(){let j=await (await fetch('/api/status')).json();"
"document.getElementById('devst').innerHTML='电量 '+(j.battery<0?'未接电池':j.battery+'%')+' · 空闲堆 '+j.heap+'B<br>开机 '+j.boot+' 次 · IP '+j.ip+'<br>WiFi '+(j.wifi?'已连':'未连')+' · '+esc(j.ssid)+'<br>时间 '+j.date+' '+j.time+'<br>天气 '+esc(j.weather);}"
"devst();"
"todoLoad();"
"async function cloudLoad(){try{let j=await (await fetch('/api/cloud')).json();"
"document.getElementById('cloud_on').checked=j.on?1:0;document.getElementById('cloud_pid').value=j.pid||'';"
"document.getElementById('cloud_name').value=j.name||'';document.getElementById('cloud_key').value=j.key||'';"
"document.getElementById('cloud_st').textContent=j.online?'已连接':'未连接';}catch(e){}}"
"async function cloudSave(){let b={on:document.getElementById('cloud_on').checked?1:0,"
"pid:document.getElementById('cloud_pid').value.trim(),name:document.getElementById('cloud_name').value.trim(),"
"key:document.getElementById('cloud_key').value};"
"let j=await (await post('/api/cloud',b)).json();"
"document.getElementById('msg').textContent=j.ok?'✓ 云端配置已保存':'保存失败(检查三元组格式: 仅字母数字-_/开启需填齐)';cloudLoad();}"
"cloudLoad();"
"load();</script></body></html>";